-- ============================================================
-- 010_seed_initiatives.sql
-- Seed 12 Programs + 88 Initiatives
-- Safe to run multiple times (ON CONFLICT DO UPDATE)
-- ============================================================

-- ── Programs ──
INSERT INTO programs (code, name, description, icon, order_index) VALUES
  ('A', 'OT/Factory Modernization & Security', 'Establish secure OT foundations (segmentation, access controls) to protect ICS/SCADA environments. Enable safe OT–IT data exchange to support monitoring, analytics and future automation.', '🏭', 1),
  ('B', 'Network Modernization & Site Connectivity', 'Upgrade backbone, switching and routing to improve reliability, performance and capacity. Expand WAN capacity and strengthen internet gateway resiliency.', '🌐', 2),
  ('C', 'Data Center, Storage & Backup/DR Resilience', 'Improve business continuity with DR readiness, geo-redundancy and operational drills. Modernize storage and backup platforms.', '🏢', 3),
  ('D', 'Cloud Foundations & Digital Platforms', 'Define scalable cloud foundations (landing zone, private connectivity) for secure hosting. Modernize digital platforms and strengthen operational security.', '☁️', 4),
  ('E', 'Collaboration & Content Modernization', 'Adopt modern productivity and collaboration platforms and migrate content to cloud services. Establish governance for identity/device management.', '📧', 5),
  ('F', 'Security Hardening & Compliance Enablement', 'Reduce attack surface with access controls, patch discipline and authentication hardening. Enable audit readiness through assessments and security tooling.', '🔒', 6),
  ('G', 'Automation, Analytics & Business Enablement', 'Automate repeatable processes to reduce manual effort. Enable analytics platforms and dashboards to improve decision-making and reporting.', '🤖', 7),
  ('H', 'Business Applications, FinTech Integrations & Governance', 'Enable critical integrations and portals to streamline business workflows and compliance. Support finance process digitization.', '💼', 8),
  ('I', 'Physical Security & Surveillance Modernization', 'Centralize surveillance operations to improve monitoring and incident response. Extend coverage to warehouses and remote sites.', '📹', 9),
  ('J', 'IT Asset Management & Operational Efficiency', 'Improve endpoint and asset lifecycle governance and operational efficiency. Modernize OS baselines and optimize support tooling.', '💻', 10),
  ('K', 'Assessments, Due Diligence & Strategy/POCs', 'Run structured assessments/POCs to select fit-for-purpose technologies and reduce adoption risk. Support M&A and network services assessments.', '📋', 11),
  ('L', 'Other Initiatives', 'Additional initiatives including ERP virtualization, infrastructure observability, conferencing solutions, and Active Directory upgrades.', '🔧', 12)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  icon = EXCLUDED.icon,
  order_index = EXCLUDED.order_index;

-- ── Initiatives ──
-- Helper: We need program IDs. Use a CTE approach.

-- FY 2024-25
INSERT INTO initiatives (title, slug, program_id, fiscal_year, strategic_area, criticality, delivery_focus, status, order_index) VALUES
  ('Industrial OT Network Segmentation (IEC 62443)', '1-industrial-ot-network-segmentation-iec-62443', (SELECT id FROM programs WHERE code='A'), '2024-25', 'OT Security', 'Critical', 'Define requirements and target controls; Coordinate design/implementation and validation; Drive governance and operational handover', 'published', 1),
  ('AI-Driven Energy Analytics & Automation', '2-ai-driven-energy-analytics-automation', (SELECT id FROM programs WHERE code='A'), '2024-25', 'IoT / Sustainability', 'High', 'Requirements and stakeholder alignment; Delivery coordination and governance; Operational handover and improvement', 'published', 2),
  ('Unified Enterprise Wi-Fi 6 Rollout (Multi-Site)', '3-unified-enterprise-wi-fi-6-rollout-multi-site', (SELECT id FROM programs WHERE code='B'), '2024-25', 'Network Infra', 'High', 'Assess capacity and performance gaps; Plan/design upgrade and coordinate implementation; Stabilize operations and document standards', 'published', 3),
  ('SharePoint & OneDrive Business Implementation', '4-sharepoint-onedrive-business-implementation', (SELECT id FROM programs WHERE code='E'), '2024-25', 'Cloud Collab', 'High', 'Define migration/adoption approach; Govern permissions/governance and rollout; Improve collaboration and reduce legacy dependency', 'published', 4),
  ('Cloud Landing Zone Architecture Design', '5-cloud-landing-zone-architecture-design', (SELECT id FROM programs WHERE code='D'), '2024-25', 'Cloud Strategy', 'Critical', 'Define cloud target architecture and governance; Coordinate connectivity/migration and security baseline; Enable operations and cost oversight', 'published', 5),
  ('Centralized IP-Surveillance (Warehousing)', '6-centralized-ip-surveillance-warehousing', (SELECT id FROM programs WHERE code='I'), '2024-25', 'Physical Security', 'High', 'Define requirements and target controls; Coordinate design/implementation and validation; Drive governance and operational handover', 'published', 6),
  ('Remote Construction Site Surveillance System', '7-remote-construction-site-surveillance-system', (SELECT id FROM programs WHERE code='I'), '2024-25', 'Physical Security', 'Medium', 'Define requirements and target controls; Coordinate design/implementation and validation; Drive governance and operational handover', 'published', 7),
  ('High-Density Fiber Distribution Hub Design', '8-high-density-fiber-distribution-hub-design', (SELECT id FROM programs WHERE code='C'), '2024-25', 'Data Center Infra', 'Critical', 'Assess current state and risks; Coordinate modernization/migration and testing; Operationalize with SOPs and monitoring', 'published', 8),
  ('Core Network Switch Lifecycle Replacement (EOL)', '9-core-network-switch-lifecycle-replacement-eol', (SELECT id FROM programs WHERE code='B'), '2024-25', 'Network Infra', 'Critical', 'Assess capacity and performance gaps; Plan/design upgrade and coordinate implementation; Stabilize operations and document standards', 'published', 9),
  -- FY 2023-24
  ('Corporate Web Asset Cloud Migration (AWS/Azure)', '10-corporate-web-asset-cloud-migration-aws-azure', (SELECT id FROM programs WHERE code='D'), '2023-24', 'Cloud / Digital', 'High', 'Define cloud target architecture and governance; Coordinate connectivity/migration and security baseline; Enable operations and cost oversight', 'published', 10),
  ('OT Network Security Roadmap Planning', '11-ot-network-security-roadmap-planning', (SELECT id FROM programs WHERE code='A'), '2023-24', 'OT Security', 'Critical', 'Define requirements and target controls; Coordinate design/implementation and validation; Drive governance and operational handover', 'published', 11),
  ('Energy Compliance & Monitoring Blueprint', '12-energy-compliance-monitoring-blueprint', (SELECT id FROM programs WHERE code='K'), '2023-24', 'Compliance', 'High', 'Requirements and stakeholder alignment; Delivery coordination and governance; Operational handover and improvement', 'published', 12),
  ('Centralized Infrastructure Hosting Assessment', '13-centralized-infrastructure-hosting-assessment', (SELECT id FROM programs WHERE code='D'), '2023-24', 'Strategy', 'Critical', 'Requirements and stakeholder alignment; Delivery coordination and governance; Operational handover and improvement', 'published', 13),
  ('Enterprise Windows 11 OS Transition', '14-enterprise-windows-11-os-transition', (SELECT id FROM programs WHERE code='J'), '2023-24', 'End-User Compute', 'Medium', 'Requirements and stakeholder alignment; Delivery coordination and governance; Operational handover and improvement', 'published', 14),
  ('Legacy Server OS Modernization (2012R2)', '15-legacy-server-os-modernization-2012r2', (SELECT id FROM programs WHERE code='J'), '2023-24', 'Infrastructure', 'High', 'Assess current state and risks; Coordinate modernization/migration and testing; Operationalize with SOPs and monitoring', 'published', 15),
  ('Dark Fiber WAN Capacity Expansion', '16-dark-fiber-wan-capacity-expansion', (SELECT id FROM programs WHERE code='B'), '2023-24', 'Network Infra', 'High', 'Assess capacity and performance gaps; Plan/design upgrade and coordinate implementation; Stabilize operations and document standards', 'published', 16),
  ('Infrastructure Observability Suite (Zabbix)', '17-infrastructure-observability-suite-zabbix', (SELECT id FROM programs WHERE code='L'), '2023-24', 'ITOps / Monitoring', 'High', 'Identify high-value use cases and requirements; Implement tooling/dashboards/bots and validate; Embed operations and continuous improvement', 'published', 17),
  -- FY 2022-23
  ('Mission-Critical ERP Server Virtualization', '18-mission-critical-erp-server-virtualization', (SELECT id FROM programs WHERE code='L'), '2022-23', 'Infrastructure', 'Critical', 'Assess current state and risks; Coordinate modernization/migration and testing; Operationalize with SOPs and monitoring', 'published', 18),
  ('EHS Incident Management SaaS Evaluation', '19-ehs-incident-management-saas-evaluation', (SELECT id FROM programs WHERE code='K'), '2022-23', 'Compliance', 'Medium', 'Requirements and stakeholder alignment; Delivery coordination and governance; Operational handover and improvement', 'published', 19),
  ('Real-time Utility Monitoring System (IoT)', '20-real-time-utility-monitoring-system-iot', (SELECT id FROM programs WHERE code='A'), '2022-23', 'Sustainability', 'Medium', 'Requirements and stakeholder alignment; Delivery coordination and governance; Operational handover and improvement', 'published', 20),
  ('Core Backbone Upgrade (1G to 10G Switching)', '21-core-backbone-upgrade-1g-to-10g-switching', (SELECT id FROM programs WHERE code='B'), '2022-23', 'Network Infra', 'Critical', 'Assess capacity and performance gaps; Plan/design upgrade and coordinate implementation; Stabilize operations and document standards', 'published', 21),
  ('Financial MIS Analytics Dashboard Development', '22-financial-mis-analytics-dashboard-development', (SELECT id FROM programs WHERE code='G'), '2022-23', 'Data Analytics', 'High', 'Identify high-value use cases and requirements; Implement tooling/dashboards/bots and validate; Embed operations and continuous improvement', 'published', 22),
  ('Enterprise Monitoring Visualization Deployment', '23-enterprise-monitoring-visualization-deployment', (SELECT id FROM programs WHERE code='G'), '2022-23', 'ITOps', 'Low', 'Identify high-value use cases and requirements; Implement tooling/dashboards/bots and validate; Embed operations and continuous improvement', 'published', 23),
  ('Branch Office Managed Network Services Assessment', '24-branch-office-managed-network-services-assessment', (SELECT id FROM programs WHERE code='K'), '2022-23', 'Network Ops', 'Medium', 'Assess capacity and performance gaps; Plan/design upgrade and coordinate implementation; Stabilize operations and document standards', 'published', 24),
  ('RPA Deployment (Attended & Unattended Bots)', '25-rpa-deployment-attended-unattended-bots', (SELECT id FROM programs WHERE code='G'), '2022-23', 'Automation', 'High', 'Identify high-value use cases and requirements; Implement tooling/dashboards/bots and validate; Embed operations and continuous improvement', 'published', 25),
  ('Edge Router Infrastructure Refresh (Cisco)', '26-edge-router-infrastructure-refresh-cisco', (SELECT id FROM programs WHERE code='B'), '2022-23', 'Network Infra', 'High', 'Assess capacity and performance gaps; Plan/design upgrade and coordinate implementation; Stabilize operations and document standards', 'published', 26),
  ('Hybrid Boardroom Conferencing Solution (Polycom)', '27-hybrid-boardroom-conferencing-solution-polycom', (SELECT id FROM programs WHERE code='L'), '2022-23', 'AV / Collab', 'Medium', 'Define coverage and operational requirements; Coordinate implementation and integration; Centralize monitoring/support model', 'published', 27),
  ('Centralized Patch Management (WSUS) Rollout', '28-centralized-patch-management-wsus-rollout', (SELECT id FROM programs WHERE code='F'), '2022-23', 'Security Ops', 'Critical', 'Define requirements and target controls; Coordinate design/implementation and validation; Drive governance and operational handover', 'published', 28),
  ('Legacy Data Center Decommissioning (Floor 1)', '29-legacy-data-center-decommissioning-floor-1', (SELECT id FROM programs WHERE code='C'), '2022-23', 'Infrastructure', 'Medium', 'Assess current state and risks; Coordinate modernization/migration and testing; Operationalize with SOPs and monitoring', 'published', 29),
  ('Cloud Storage Migration (OneDrive/SharePoint)', '30-cloud-storage-migration-onedrive-sharepoint', (SELECT id FROM programs WHERE code='E'), '2022-23', 'Cloud Storage', 'High', 'Define migration/adoption approach; Govern permissions/governance and rollout; Improve collaboration and reduce legacy dependency', 'published', 30),
  ('File Server to Cloud Content Migration', '31-file-server-to-cloud-content-migration', (SELECT id FROM programs WHERE code='E'), '2022-23', 'Data Mgmt', 'Medium', 'Define migration/adoption approach; Govern permissions/governance and rollout; Improve collaboration and reduce legacy dependency', 'published', 31),
  ('PowerBI Analytics Platform Procurement', '32-powerbi-analytics-platform-procurement', (SELECT id FROM programs WHERE code='G'), '2022-23', 'BI / Analytics', 'Medium', 'Identify high-value use cases and requirements; Implement tooling/dashboards/bots and validate; Embed operations and continuous improvement', 'published', 32),
  ('Microsoft 365 & Intune MDM Procurement', '33-microsoft-365-intune-mdm-procurement', (SELECT id FROM programs WHERE code='E'), '2022-23', 'Cloud / Security', 'Critical', 'Define requirements and target controls; Coordinate design/implementation and validation; Drive governance and operational handover', 'published', 33),
  ('Managed Print Services Implementation', '34-managed-print-services-implementation', (SELECT id FROM programs WHERE code='J'), '2022-23', 'Ops Efficiency', 'Low', 'Requirements and stakeholder alignment; Delivery coordination and governance; Operational handover and improvement', 'published', 34),
  ('IT Asset Lifecycle Management System', '35-it-asset-lifecycle-management-system', (SELECT id FROM programs WHERE code='J'), '2022-23', 'ITAM', 'Medium', 'Requirements and stakeholder alignment; Delivery coordination and governance; Operational handover and improvement', 'published', 35),
  -- FY 2021-22
  ('Disaster Recovery Geo-Redundancy Migration', '36-disaster-recovery-geo-redundancy-migration', (SELECT id FROM programs WHERE code='C'), '2021-22', 'BCP / DR', 'Critical', 'Assess current state and risks; Coordinate modernization/migration and testing; Operationalize with SOPs and monitoring', 'published', 36),
  ('Robotic Process Automation (Scale-out Phase)', '37-robotic-process-automation-scale-out-phase', (SELECT id FROM programs WHERE code='G'), '2021-22', 'Automation', 'High', 'Identify high-value use cases and requirements; Implement tooling/dashboards/bots and validate; Embed operations and continuous improvement', 'published', 37),
  ('ERP Landscape Virtualization (Dev/QA/Prod)', '38-erp-landscape-virtualization-dev-qa-prod', (SELECT id FROM programs WHERE code='L'), '2021-22', 'Infrastructure', 'Critical', 'Assess current state and risks; Coordinate modernization/migration and testing; Operationalize with SOPs and monitoring', 'published', 38),
  ('Subsidiary IT Infrastructure Due Diligence', '39-subsidiary-it-infrastructure-due-diligence', (SELECT id FROM programs WHERE code='K'), '2021-22', 'M&A Strategy', 'High', 'Requirements and stakeholder alignment; Delivery coordination and governance; Operational handover and improvement', 'published', 39),
  ('Microsoft 365 Enterprise Rollout', '40-microsoft-365-enterprise-rollout', (SELECT id FROM programs WHERE code='E'), '2021-22', 'Cloud Productivity', 'High', 'Define migration/adoption approach; Govern permissions/governance and rollout; Improve collaboration and reduce legacy dependency', 'published', 40),
  ('Hybrid Cloud Connectivity (Azure ExpressRoute)', '41-hybrid-cloud-connectivity-azure-expressroute', (SELECT id FROM programs WHERE code='D'), '2021-22', 'Cloud Network', 'Critical', 'Assess capacity and performance gaps; Plan/design upgrade and coordinate implementation; Stabilize operations and document standards', 'published', 41),
  ('Enterprise Backup & Storage Enhancement', '42-enterprise-backup-storage-enhancement', (SELECT id FROM programs WHERE code='C'), '2021-22', 'Data Protection', 'Critical', 'Assess current state and risks; Coordinate modernization/migration and testing; Operationalize with SOPs and monitoring', 'published', 42),
  ('Corporate Governance Portal Go-Live', '43-corporate-governance-portal-go-live', (SELECT id FROM programs WHERE code='H'), '2021-22', 'Compliance', 'Medium', 'Requirements and stakeholder alignment; Delivery coordination and governance; Operational handover and improvement', 'published', 43),
  ('Corporate Web Maintenance & Security Patching', '44-corporate-web-maintenance-security-patching', (SELECT id FROM programs WHERE code='D'), '2021-22', 'Web Ops', 'Low', 'Requirements and stakeholder alignment; Delivery coordination and governance; Operational handover and improvement', 'published', 44),
  ('Banking Interface Integration (NCHL/ERP)', '45-banking-interface-integration-nchl-erp', (SELECT id FROM programs WHERE code='H'), '2021-22', 'FinTech Integration', 'Critical', 'Requirements and stakeholder alignment; Delivery coordination and governance; Operational handover and improvement', 'published', 45),
  ('Automated EFT Payment Gateway Integration', '46-automated-eft-payment-gateway-integration', (SELECT id FROM programs WHERE code='H'), '2021-22', 'FinTech Integration', 'Critical', 'Requirements and stakeholder alignment; Delivery coordination and governance; Operational handover and improvement', 'published', 46),
  ('IT Asset Disposal & Write-off Governance', '47-it-asset-disposal-write-off-governance', (SELECT id FROM programs WHERE code='J'), '2021-22', 'ITAM / Compliance', 'Low', 'Requirements and stakeholder alignment; Delivery coordination and governance; Operational handover and improvement', 'published', 47),
  ('Financial Accounting Tool Implementation', '48-financial-accounting-tool-implementation', (SELECT id FROM programs WHERE code='H'), '2021-22', 'Finance Apps', 'High', 'Requirements and stakeholder alignment; Delivery coordination and governance; Operational handover and improvement', 'published', 48),
  ('Tableau BI Infrastructure Setup', '49-tableau-bi-infrastructure-setup', (SELECT id FROM programs WHERE code='G'), '2021-22', 'Data Analytics', 'High', 'Identify high-value use cases and requirements; Implement tooling/dashboards/bots and validate; Embed operations and continuous improvement', 'published', 49),
  ('Internal PKI & CA Certificate Deployment', '50-internal-pki-ca-certificate-deployment', (SELECT id FROM programs WHERE code='F'), '2021-22', 'Cybersecurity', 'High', 'Define requirements and target controls; Coordinate design/implementation and validation; Drive governance and operational handover', 'published', 50),
  -- FY 2020-21
  ('Disk-Based Backup Modernization', '51-disk-based-backup-modernization', (SELECT id FROM programs WHERE code='C'), '2020-21', 'Data Protection', 'Critical', 'Assess current state and risks; Coordinate modernization/migration and testing; Operationalize with SOPs and monitoring', 'published', 51),
  ('High-Performance Storage Migration (Flash)', '52-high-performance-storage-migration-flash', (SELECT id FROM programs WHERE code='C'), '2020-21', 'Infrastructure', 'Critical', 'Assess current state and risks; Coordinate modernization/migration and testing; Operationalize with SOPs and monitoring', 'published', 52),
  ('Network Access Control (RADIUS/802.1x)', '53-network-access-control-radius-802-1x', (SELECT id FROM programs WHERE code='F'), '2020-21', 'Cybersecurity', 'Critical', 'Define requirements and target controls; Coordinate design/implementation and validation; Drive governance and operational handover', 'published', 53),
  ('Office 365 Initial Pilot & Deployment', '54-office-365-initial-pilot-deployment', (SELECT id FROM programs WHERE code='E'), '2020-21', 'Cloud Productivity', 'High', 'Define migration/adoption approach; Govern permissions/governance and rollout; Improve collaboration and reduce legacy dependency', 'published', 54),
  ('Corporate Website Technology Upgrade', '55-corporate-website-technology-upgrade', (SELECT id FROM programs WHERE code='D'), '2020-21', 'Digital', 'Medium', 'Requirements and stakeholder alignment; Delivery coordination and governance; Operational handover and improvement', 'published', 55),
  ('Enterprise Digital Rights Management (DRM)', '56-enterprise-digital-rights-management-drm', (SELECT id FROM programs WHERE code='F'), '2020-21', 'Data Security', 'Critical', 'Define requirements and target controls; Coordinate design/implementation and validation; Drive governance and operational handover', 'published', 56),
  ('RPA: IT Service Desk & Finance Automation', '57-rpa-it-service-desk-finance-automation', (SELECT id FROM programs WHERE code='G'), '2020-21', 'Automation', 'High', 'Identify high-value use cases and requirements; Implement tooling/dashboards/bots and validate; Embed operations and continuous improvement', 'published', 57),
  ('Management Information System (MIS) Portal', '58-management-information-system-mis-portal', (SELECT id FROM programs WHERE code='H'), '2020-21', 'Applications', 'Medium', 'Requirements and stakeholder alignment; Delivery coordination and governance; Operational handover and improvement', 'published', 58),
  ('E-Governance Policy Portal', '59-e-governance-policy-portal', (SELECT id FROM programs WHERE code='H'), '2020-21', 'Compliance', 'Medium', 'Requirements and stakeholder alignment; Delivery coordination and governance; Operational handover and improvement', 'published', 59),
  ('Interim Disaster Recovery Site Setup', '60-interim-disaster-recovery-site-setup', (SELECT id FROM programs WHERE code='C'), '2020-21', 'BCP / DR', 'Critical', 'Assess current state and risks; Coordinate modernization/migration and testing; Operationalize with SOPs and monitoring', 'published', 60),
  ('DMZ Network Virtualization', '61-dmz-network-virtualization', (SELECT id FROM programs WHERE code='F'), '2020-21', 'Network Security', 'High', 'Define requirements and target controls; Coordinate design/implementation and validation; Drive governance and operational handover', 'published', 61),
  -- FY 2019-20
  ('Zero-Impact ERP OS Migration', '62-zero-impact-erp-os-migration', (SELECT id FROM programs WHERE code='L'), '2019-20', 'Infrastructure', 'Critical', 'Assess current state and risks; Coordinate modernization/migration and testing; Operationalize with SOPs and monitoring', 'published', 62),
  ('Legacy Storage Platform Replacement', '63-legacy-storage-platform-replacement', (SELECT id FROM programs WHERE code='C'), '2019-20', 'Infrastructure', 'Critical', 'Assess current state and risks; Coordinate modernization/migration and testing; Operationalize with SOPs and monitoring', 'published', 63),
  ('Backup Workflow Redesign & Tool Upgrade', '64-backup-workflow-redesign-tool-upgrade', (SELECT id FROM programs WHERE code='C'), '2019-20', 'Data Protection', 'High', 'Assess current state and risks; Coordinate modernization/migration and testing; Operationalize with SOPs and monitoring', 'published', 64),
  ('Windows Server OS Risk Remediation', '65-windows-server-os-risk-remediation', (SELECT id FROM programs WHERE code='J'), '2019-20', 'Infrastructure', 'High', 'Assess current state and risks; Coordinate modernization/migration and testing; Operationalize with SOPs and monitoring', 'published', 65),
  ('IT Asset Management Portal Implementation', '66-it-asset-management-portal-implementation', (SELECT id FROM programs WHERE code='J'), '2019-20', 'ITAM', 'Low', 'Requirements and stakeholder alignment; Delivery coordination and governance; Operational handover and improvement', 'published', 66),
  ('Backup Solution Proof of Concept (POC)', '67-backup-solution-proof-of-concept-poc', (SELECT id FROM programs WHERE code='K'), '2019-20', 'Technology Eval', 'Low', 'Requirements and stakeholder alignment; Delivery coordination and governance; Operational handover and improvement', 'published', 67),
  ('Network AAA Security Implementation', '68-network-aaa-security-implementation', (SELECT id FROM programs WHERE code='F'), '2019-20', 'Cybersecurity', 'Critical', 'Define requirements and target controls; Coordinate design/implementation and validation; Drive governance and operational handover', 'published', 68),
  ('VSS Clone Endpoint Deployment Optimization', '69-vss-clone-endpoint-deployment-optimization', (SELECT id FROM programs WHERE code='J'), '2019-20', 'ITOps Efficiency', 'Medium', 'Identify high-value use cases and requirements; Implement tooling/dashboards/bots and validate; Embed operations and continuous improvement', 'published', 69),
  ('Remote Support Services Implementation', '70-remote-support-services-implementation', (SELECT id FROM programs WHERE code='J'), '2019-20', 'ITOps', 'Low', 'Identify high-value use cases and requirements; Implement tooling/dashboards/bots and validate; Embed operations and continuous improvement', 'published', 70),
  ('Greenfield Factory IT Infrastructure Design', '71-greenfield-factory-it-infrastructure-design', (SELECT id FROM programs WHERE code='J'), '2019-20', 'Infrastructure', 'High', 'Assess current state and risks; Coordinate modernization/migration and testing; Operationalize with SOPs and monitoring', 'published', 71),
  -- FY 2018-19
  ('3-Zone Security Virtualization Initiative', '72-3-zone-security-virtualization-initiative', (SELECT id FROM programs WHERE code='K'), '2018-19', 'Infrastructure', 'Critical', 'Assess current state and risks; Coordinate modernization/migration and testing; Operationalize with SOPs and monitoring', 'published', 72),
  ('DMZ Server Consolidation', '73-dmz-server-consolidation', (SELECT id FROM programs WHERE code='K'), '2018-19', 'Infrastructure', 'High', 'Assess current state and risks; Coordinate modernization/migration and testing; Operationalize with SOPs and monitoring', 'published', 73),
  ('Border Router & Internet Gateway Upgrade', '74-border-router-internet-gateway-upgrade', (SELECT id FROM programs WHERE code='B'), '2018-19', 'Network Infra', 'Critical', 'Assess capacity and performance gaps; Plan/design upgrade and coordinate implementation; Stabilize operations and document standards', 'published', 74),
  ('Factory IT Infrastructure Procurement', '75-factory-it-infrastructure-procurement', (SELECT id FROM programs WHERE code='J'), '2018-19', 'Infrastructure', 'High', 'Assess current state and risks; Coordinate modernization/migration and testing; Operationalize with SOPs and monitoring', 'published', 75),
  ('Warehouse IT Infrastructure Setup (Redundant)', '76-warehouse-it-infrastructure-setup-redundant', (SELECT id FROM programs WHERE code='J'), '2018-19', 'Infrastructure', 'High', 'Assess current state and risks; Coordinate modernization/migration and testing; Operationalize with SOPs and monitoring', 'published', 76),
  ('Automated User Acceptance System (Lotus)', '77-automated-user-acceptance-system-lotus', (SELECT id FROM programs WHERE code='H'), '2018-19', 'Applications', 'Low', 'Requirements and stakeholder alignment; Delivery coordination and governance; Operational handover and improvement', 'published', 77),
  ('Microsoft RAP Security Assessment', '78-microsoft-rap-security-assessment', (SELECT id FROM programs WHERE code='F'), '2018-19', 'Cybersecurity', 'High', 'Define requirements and target controls; Coordinate design/implementation and validation; Drive governance and operational handover', 'published', 78),
  ('Remote Assistance (MSRA) Deployment', '79-remote-assistance-msra-deployment', (SELECT id FROM programs WHERE code='J'), '2018-19', 'End-User Support', 'Low', 'Requirements and stakeholder alignment; Delivery coordination and governance; Operational handover and improvement', 'published', 79),
  ('Active Directory Security Audit', '80-active-directory-security-audit', (SELECT id FROM programs WHERE code='F'), '2018-19', 'Cybersecurity', 'High', 'Define requirements and target controls; Coordinate design/implementation and validation; Drive governance and operational handover', 'published', 80),
  -- FY 2017-18
  ('Virtualization Procurement & Planning', '81-virtualization-procurement-planning', (SELECT id FROM programs WHERE code='K'), '2017-18', 'Strategy', 'Medium', 'Requirements and stakeholder alignment; Delivery coordination and governance; Operational handover and improvement', 'published', 81),
  ('Infrastructure Monitoring Tool Pilot', '82-infrastructure-monitoring-tool-pilot', (SELECT id FROM programs WHERE code='K'), '2017-18', 'Monitoring', 'Medium', 'Identify high-value use cases and requirements; Implement tooling/dashboards/bots and validate; Embed operations and continuous improvement', 'published', 82),
  ('High-Availability (N+1) Infrastructure Redesign', '83-high-availability-n-1-infrastructure-redesign', (SELECT id FROM programs WHERE code='C'), '2017-18', 'Infrastructure', 'Critical', 'Assess current state and risks; Coordinate modernization/migration and testing; Operationalize with SOPs and monitoring', 'published', 83),
  ('Windows 10 & Office 2013 Migration', '84-windows-10-office-2013-migration', (SELECT id FROM programs WHERE code='J'), '2017-18', 'End-User Compute', 'High', 'Requirements and stakeholder alignment; Delivery coordination and governance; Operational handover and improvement', 'published', 84),
  ('Active Directory Functional Level Upgrade', '85-active-directory-functional-level-upgrade', (SELECT id FROM programs WHERE code='L'), '2017-18', 'Infrastructure', 'Critical', 'Assess current state and risks; Coordinate modernization/migration and testing; Operationalize with SOPs and monitoring', 'published', 85),
  ('Centralized Surveillance Operations Center', '86-centralized-surveillance-operations-center', (SELECT id FROM programs WHERE code='I'), '2017-18', 'Physical Security', 'High', 'Define requirements and target controls; Coordinate design/implementation and validation; Drive governance and operational handover', 'published', 86),
  -- FY 2016-17
  ('Multi-Site CCTV Implementation (Phase 1)', '87-multi-site-cctv-implementation-phase-1', (SELECT id FROM programs WHERE code='I'), '2016-17', 'Physical Security', 'Medium', 'Define requirements and target controls; Coordinate design/implementation and validation; Drive governance and operational handover', 'published', 87),
  ('Virtualization Technology POC', '88-virtualization-technology-poc', (SELECT id FROM programs WHERE code='K'), '2016-17', 'Technology Eval', 'Low', 'Requirements and stakeholder alignment; Delivery coordination and governance; Operational handover and improvement', 'published', 88)
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  program_id = EXCLUDED.program_id,
  fiscal_year = EXCLUDED.fiscal_year,
  strategic_area = EXCLUDED.strategic_area,
  criticality = EXCLUDED.criticality,
  delivery_focus = EXCLUDED.delivery_focus,
  status = EXCLUDED.status,
  order_index = EXCLUDED.order_index;
